Make responsive layoute and make card popular articel to same size
codescapes-io/codescapes-io.github.io pull request #15
Opened 2022-02-02 05:05 UTC by ibramgusti

close : #12 #11 

maaf pak kemarin lupa belum merge dari master jadi yang kemarin ngikut semua

2022-02-02 05:19 UTC, rennols requested changes

2022-02-02 05:19 UTC, rennols commented on public/index.html
> +<head>
identationya berantakan lagi

2022-02-02 05:19 UTC, rennols commented on src/component/CSNavbar.tsx
> +// import CSArticle from '../view/CSArticle';
remove comment

2022-02-02 05:19 UTC, rennols commented on src/component/CSNavbar.tsx
> +                {/* <Route path='/blog/:id' element={<CSArticle />} /> */}
remove comment

2022-02-03 06:35 UTC, ibramgusti commented
close #14

2022-02-03 06:45 UTC, rennols requested changes
indentationya beda beda ya, tolong disamain ke 2 space semua

2022-02-03 06:45 UTC, rennols commented on package-lock.json
>          "resolve": "^1.21.0"
tailwind udah ngga dipake kan? uninstall aja

2022-02-03 06:45 UTC, rennols commented on src/App.css
> +
ini kosong? hapus aja

2022-02-03 06:45 UTC, rennols commented on src/assets/style/CSBlogPage.css
> +@media screen and (min-width: 1024px) {
ini juga kosong, hapus aja

2022-02-03 06:45 UTC, rennols commented on src/assets/style/CSHomePage.css
> +@media screen and (min-width: 1024px) {
ini kosong hapus aja

2022-02-03 06:45 UTC, rennols commented on src/component/CSHeroSlider.tsx
>      let month = ["January", "February", "March", "April", "May", "June",
ini variable ditempat lain udah ada, jadiin 1 aja biar ga define ulang

2022-02-03 06:45 UTC, rennols commented on src/component/CSNavbar.tsx
> +    const [drawer, setDrawer] = useState(false);
variable kurang bisa dimengerti, apa maksudnya `drawer` dengan tipe boolean?

2022-02-03 06:45 UTC, rennols commented on src/index.css
> +@tailwind utilities;
tailwind hapus

2022-02-03 06:45 UTC, rennols commented on tailwind.config.js
> +module.exports = {
hapus tailwind

2022-02-03 07:46 UTC, rennols requested changes

2022-02-03 07:46 UTC, rennols commented on src/component/CSHeroSlider.tsx
> +    // let formatDate = `${date.getDay()}  ${month[date.getMonth()]}  ${date.getFullYear()}`
remove comment

2022-02-03 08:00 UTC, rennols approved these changes

2022-02-03 08:01 UTC, rennols requested changes
beberapa comment belum difix

2022-02-03 09:56 UTC, ibramgusti commented
> beberapa comment belum difix

comment yg mana pak?

2022-02-04 01:50 UTC, rennols approved these changes

2022-02-04 01:51 UTC, merged