Add article page
codescapes-io/codescapes-io.github.io pull request #20
Opened 2022-02-04 09:35 UTC by ibramgusti

2022-02-08 06:04 UTC, rennols requested changes
Penamaan class dll tolong disesuaikan dengan ketentuan
interface kasih prefix CSI dst

2022-02-08 06:04 UTC, rennols commented on src/view/CSArticle.tsx
> +            const response = await axios.get(`${process.env.REACT_APP_BASE_URL}/api/articles/${id}?populate=categories,users_permissions_user`)
disini bisa langsung kasih typenya

aku gatau detail strukturnya, ntar di sesuain aja
```js
// outside component
export interface CSIArticleListResponse {
    data: {
        data: CSIArticleList
    }
}

//inside component
const response = await axios.get<CSIArticleListResponse>(`${process.env.REACT_APP_BASE_URL}/api/articles/${id}?populate=categories,users_permissions_user`)
```

2022-02-08 08:48 UTC, ibramgusti commented
ini saya make struktur mock yg sama spt di BlogPage tapi kok yg di HomePage error ya pak, errornya di ngga kebaca response.data nya

2022-02-08 08:59 UTC, rennols requested changes
comment2 yang ngga ngebantu hapus aja

2022-02-08 08:59 UTC, rennols commented on src/component/CSCardArticle.tsx
>      id?: number
tambahin prefix, n untuk number, str untuk string

2022-02-08 08:59 UTC, rennols commented on src/component/Navbar/__test__/CSNavbar.test.tsx
> +        // render
komen ini ngga ngebantu, kita tau itu render, knp dikasih komen render? hapus aja

2022-02-08 08:59 UTC, rennols commented on src/view/CSBlogPage/CSBlogPage.tsx
> +export interface CSICategoriesProps {
kan tadi udah di comment, ini bukan props jangan dikasih suffix props

2022-02-08 08:59 UTC, rennols commented on src/view/CSBlogPage/CSBlogPage.tsx
> +    const [articles, setArticles] = useState<CSIArticleListProps['data']>([]);
kalo udah typing, aksesnya pake . aja jangan []
CSIArticleListProps.data

2022-02-08 08:59 UTC, rennols commented on src/view/CSBlogPage/CSBlogPage.tsx
>  }
ini harusnya response, tadi kan di comment juga cukup jelas
CSIArticleResponse
CSIArticleListResponse

2022-02-08 09:00 UTC, rennols commented
> ini saya make struktur mock yg sama spt di BlogPage tapi kok yg di HomePage error ya pak, errornya di ngga kebaca response.data nya

kemungkinan typingnya salah, coba dicek disitu

2022-02-08 09:20 UTC, ibramgusti commented on src/view/CSBlogPage/CSBlogPage.tsx
> +    const [articles, setArticles] = useState<CSIArticleListProps['data']>([]);
jadinya 
```js
useState<CSIArticleListResponse.data>(...)
```
gini pak?

2022-02-08 09:35 UTC, rennols commented on src/view/CSBlogPage/CSBlogPage.tsx
> +    const [articles, setArticles] = useState<CSIArticleListProps['data']>([]);
engga juga sih ya, harusnya bisa pake yang CSIArticle

2022-02-08 09:45 UTC, ibramgusti commented on src/view/CSBlogPage/CSBlogPage.tsx
> +    const [articles, setArticles] = useState<CSIArticleListProps['data']>([]);
error sih pak, soalnya didalem response.data itu ada object data lagi, jadi didalem CSIArticle harus ada object data yg ngebungkus id sama attributes

2022-02-08 09:51 UTC, rennols commented on src/view/CSBlogPage/CSBlogPage.tsx
> +    const [articles, setArticles] = useState<CSIArticleListProps['data']>([]);
ok jadi ini state buat nyimpen response? kalo emang buat nyimpen respon, pake yang CSIArticleResponse

2022-02-08 10:00 UTC, ibramgusti commented on src/view/CSBlogPage/CSBlogPage.tsx
> +    const [articles, setArticles] = useState<CSIArticleListProps['data']>([]);
jadi bener pak?
state articles itu isinya array of object[{id, attributes}, {id, attributes}, ...]
tapi hasil request dari strapi itu dibungkus lagi sama object data makanya setState nya response.data.data

2022-02-08 10:01 UTC, rennols commented on src/view/CSBlogPage/CSBlogPage.tsx
> +    const [articles, setArticles] = useState<CSIArticleListProps['data']>([]);
engga gitu
mksudku typingnya itu yang jelas, dari interface
jangan akses dalem interface
CSIArticleListResponse['data'] <- ini kan akses dalemnya interface

2022-02-08 10:23 UTC, ibramgusti commented on src/view/CSBlogPage/CSBlogPage.tsx
> +    const [articles, setArticles] = useState<CSIArticleListProps['data']>([]);
kalo saya bikin 
```js
useState<CSIArticle[]>(...) 
```
bisa kan pak @rennols ?

2022-02-08 10:24 UTC, rennols commented on src/view/CSBlogPage/CSBlogPage.tsx
> +    const [articles, setArticles] = useState<CSIArticleListProps['data']>([]);
boleh aja

2022-02-09 03:11 UTC, rennols requested changes
ada comment yang belum di resolve

2022-02-09 03:11 UTC, rennols commented on src/view/CSArticle/__test__/CSArticle.test.tsx
> +        // mock axios
comment ini juga ngga perlu sih

2022-02-09 03:11 UTC, rennols commented on src/view/CSHomePage/CSHomePage.tsx
> +    const [content, setContent] = useState<CSIHome['data']>()
kemaren udah di comment, jangan akses dalemnya interface, tapi declare interface lain

2022-02-09 04:56 UTC, rennols approved these changes

2022-02-09 04:56 UTC, merged