Create Docs page
codescapes-io/codescapes-io.github.io pull request #24
Opened 2022-02-21 09:11 UTC by ibramgusti

masih belum nemu solusi utk error di test nya sih pak, problem di reacr-markdownnya
kayanya ada problem di Jest dia ga mau read non CommonJS, maybe?
#21

2022-02-22 02:30 UTC, rennols requested changes

2022-02-22 02:30 UTC, rennols commented on src/component/CSDocsContent.tsx
> +export interface CSIDocViewRespoonse {
fix typo

2022-02-22 02:30 UTC, rennols commented on src/component/CSDocsContent.tsx
> +    const contentList = docView ? docView?.attributes.content.split('####') : []
ini split buat apa? `####` kan termasuk markdown syntax

2022-02-22 02:30 UTC, rennols commented on src/component/Layout/CSLayout.tsx
> +                {/* <Navigate to="/docs/3" /> */}
remove comment

2022-02-22 02:30 UTC, rennols commented on src/component/Layout/CSLayout.tsx
> +                <Route path='/docs' element={path === '#/docs' ? <Navigate to={'/docs/3'} /> : <CSDocsPage />}>
ini kok navigate to nya static

2022-02-22 02:30 UTC, rennols commented on src/component/Layout/CSLayout.tsx
> +                    <Route path=':doc_view' element={<CSDocsContent />} />
pathnya ganti ke `:id` aja

2022-02-22 02:30 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +}
Ini masih dipake?

2022-02-22 02:30 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +        doc_view?: {
mungkin fieldnamenya di strapi di rename ke docView aja biar seragam

2022-02-22 02:30 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +    doc_view: number
rename ke nDocViewId

2022-02-22 02:30 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +        const splittedpaths = path.split('/');
rename ke splittedPaths

2022-02-22 02:30 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +    const recurs = useCallback((path: string, maps: Map<string, CSIFormatPath>, id: number) => {
rename function ke constructNav

ikutin sesuai coding convention
prefix str buat string, n buat number

2022-02-22 02:30 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +
no new line

2022-02-22 02:30 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +            const key = splittedpaths[0];
rename strKey

2022-02-22 02:30 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +                maps.set(key, {
bikin variable dulu aja
```js
const value = {}
maps.set(strKey, value)
```

2022-02-22 02:30 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +                let view_id = parent.childs.get(strChildKey)?.doc_view ?? id
rename ke nDocViewId

2022-02-22 02:30 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +    }, [])
useCallback ada memoization, jadi set depsnya ke argument aja supaya kalo value dari argumentnya sama, dia gaperlu compute ulang

```js
[strPath, maps, nId]
```

2022-02-22 02:30 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +        maps.forEach((value, key) => {
(value, strKey)

2022-02-22 02:46 UTC, ibramgusti commented on src/component/CSDocsContent.tsx
> +    const contentList = docView ? docView?.attributes.content.split('####') : []
ini buat seleksi sub judul nya pak, contoh di Database sub judul Introduction & supported database

2022-02-22 02:51 UTC, rennols commented on src/component/CSDocsContent.tsx
> +    const contentList = docView ? docView?.attributes.content.split('####') : []
kan content isinya beda2 tuh, ada yang pake `**` itu handle gmn?
coba minta ss untuk hasilnya gmn

soalnya kan pake markdown, contohnya
# Introduction <- ini bakalan di render sebagai h1 element
jadi ngga perlu split ataupun field2 lain

2022-02-22 02:53 UTC, ibramgusti commented on src/component/Layout/CSLayout.tsx
> +                <Route path='/docs' element={path === '#/docs' ? <Navigate to={'/docs/3'} /> : <CSDocsPage />}>
niatnya ketika dia masuk ke /docs bakal navigate ke getting started

2022-02-22 02:53 UTC, ibramgusti commented on src/component/Layout/CSLayout.tsx
> +                    <Route path=':doc_view' element={<CSDocsContent />} />
line 139 pak @rennols ?

2022-02-22 02:55 UTC, rennols commented on src/component/Layout/CSLayout.tsx
> +                    <Route path=':doc_view' element={<CSDocsContent />} />
iya

2022-02-22 02:57 UTC, rennols commented on src/component/Layout/CSLayout.tsx
> +                <Route path='/docs' element={path === '#/docs' ? <Navigate to={'/docs/3'} /> : <CSDocsPage />}>
engga safe sih, kan id bisa berubah2
bikin aja single types di strapi, jadi nanti default doc index bisa di set di cms

2022-02-22 03:24 UTC, ibramgusti commented on src/component/CSDocsContent.tsx
> +    const contentList = docView ? docView?.attributes.content.split('####') : []
![image](https://user-images.githubusercontent.com/62697975/155057356-04f36c31-4378-4809-98f2-ebae70f6caaa.png)

gini pak hasilnya, aku asumsi kalo h4 itu buat sub judul

2022-02-22 03:45 UTC, rennols commented on src/component/CSDocsContent.tsx
> +    const contentList = docView ? docView?.attributes.content.split('####') : []
buat table of content?

2022-02-22 03:48 UTC, rennols commented on src/component/CSDocsContent.tsx
> +    const contentList = docView ? docView?.attributes.content.split('####') : []
kalo buat table of content brarti kan banyak kriterianya, ngga cuma ####
misal
```md
# Title

## 1. Heading
### 1.1 Heading
## 2. Heading
### 2.1 Heading
#### 2.1.1 Heading
```

kalo ada kayak gitu gmn?

2022-02-22 06:35 UTC, ibramgusti commented on src/component/CSDocsContent.tsx
> +    const contentList = docView ? docView?.attributes.content.split('####') : []
jadi table of contentnya dibikin filed sendiri di strapi atau gimana pak?

2022-02-22 07:00 UTC, rennols commented on src/component/CSDocsContent.tsx
> +    const contentList = docView ? docView?.attributes.content.split('####') : []
ya mending dari strapi aja
pastiin aja berfungsi misal di strapi bikin table of content Introduction, waktu diklik navigate ke Introduction section

2022-02-22 08:48 UTC, ibramgusti commented on src/view/CSDocsPage/CSDocsPage.tsx
> +    }, [])
kemarin saya sudah nyoba ini sih, tapi strPath, maps, sama nId nya ngga kebaca

2022-02-22 08:57 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +    }, [])
ngga kebaca gmn ya?

2022-02-22 09:02 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +    }, [])
oh karna function recursnya return void, bukan value

dibikin return list aja

2022-02-22 09:05 UTC, ibramgusti commented on src/view/CSDocsPage/CSDocsPage.tsx
> +    }, [])
`cannot find name 'strPath'`
gini sih error nya, kaya undefined

2022-02-22 09:34 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +    }, [])
ya kan strPath ini tuh dari argument, kalo argument ngga kamu ganti dari path ke strPath juga, ya error lah

2022-02-22 09:41 UTC, ibramgusti commented on src/view/CSDocsPage/CSDocsPage.tsx
> +    }, [])
udah saya ganti semua sih sesuai comment/review, kemarin juga sebelum pr make path maps id juga sama error
kalo kosong saya mikirnya bakal sekali panggil sama kaya useEffect

2022-02-22 09:44 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +    }, [])
kalo gitu ini fuction biasa aja, tapi didalemnya panggil useMemo

2022-02-22 10:30 UTC, ibramgusti commented on src/view/CSDocsPage/CSDocsPage.tsx
> +    }, [])
manggil useMemo nya dimana pak @rennols ? useMemo kalo gasalah kan dia return value ya pak sedangkan func constructNav dia ngeproses Maps

2022-02-22 10:32 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +    }, [])
> oh karna function recursnya return void, bukan value
> 
> dibikin return list aja

ya ini kan aku udah jelasin, function constructNav dibikin return list aja

2022-03-01 03:32 UTC, rennols requested changes

2022-03-01 03:32 UTC, rennols commented on src/component/Layout/CSLayout.tsx
> +    const [nDefIndex, setDefIndex] = useState<number>(3);
nDefIndex kurang jelas, kasih nama yang lebih jelas
trus knp defaultnya 3, -1 aja defaultnya

2022-03-01 03:32 UTC, rennols commented on src/component/CSDocsContent.tsx
> +    const contentList = docView ? docView?.attributes.content.split('####') : []
fix dulu

2022-03-01 03:32 UTC, rennols commented on src/component/Layout/CSLayout.tsx
> +            if (cancel || !resp) return;
semua API call harus ada handle status code diluar 200

2022-03-01 03:32 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +                console.log(err);
remove log

2022-03-01 10:11 UTC, rennols requested changes
comment lama yang belum aku mark resolved tolong dicek lagi

2022-03-01 10:11 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +                    {/* Loop to render doc list */}
komen sepertinya tidak akan diperlukan jika penamaan functionya tepat
knp ngga kasih nama functionya `renderLinkComponents`

2022-03-01 10:11 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +            const resPath = await axios.get<CSIDocPathListResponse>(`${process.env.REACT_APP_BASE_URL}/api/doc-paths?populate[doc_view][fields][0]=id`)
nama variable disesuikan, kalo hasilnya banyak, ya namanya resPaths

2022-03-01 10:11 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +            .then(paths => {
samain dengan yang lain `resp`

2022-03-01 10:11 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +
no new line

2022-03-01 10:11 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +                    {linkComponent(linkList)}
sama kayak komen terkait linkComponent

2022-03-01 10:11 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +                {drawer()}
rename jadi renderDrawer

2022-03-01 10:35 UTC, ibramgusti commented on src/component/CSDocsContent.tsx
> +                            const childs = React.Children.toArray(children)
kalau di doc react-md dia nerima `Record<string, Component>` dan kalo saya lihat di contoh use custom components dia sintaksnya juga kaya gitu pak.
trus untuk yg children itu dia bentuknya array, sebenernya make toString() bisa juga sih cuma itu saya nurut sama solusi di stack

2022-03-01 10:40 UTC, rennols commented on src/component/CSDocsContent.tsx
> +                            const childs = React.Children.toArray(children)
tapi di documentasinya bisa
![image](https://user-images.githubusercontent.com/10262370/156154138-8205150a-d7df-4790-85d5-d529c3d9c3f4.png)
`children` bukannya ReactNode? kalo `childs` array karna udah call toArray, coba di cek lagi

2022-03-01 10:42 UTC, rennols commented on src/view/CSArticle/CSArticle.tsx
> +                setContentArticle(resp.data.data.attributes.content.split('\n').filter((item: string) => item.length));
bukan, yang line 52, split('\n') trus filter dst itu tujuannya gmn?

2022-03-01 10:49 UTC, ibramgusti commented on src/component/CSDocsContent.tsx
> +                            const childs = React.Children.toArray(children)
bisa sih pak jadi h1: ({... , ...}) => { return ... }

iya pak kalo saya log dia outputnya array

2022-03-01 10:51 UTC, rennols commented on src/component/CSDocsContent.tsx
> +                            const childs = React.Children.toArray(children)
ok dibikin aja kayak gitu
hmm, trus bedanya setelah call toArray apa? kalo `children` udah array, knp call `toArray` tolong dicek

2022-03-01 10:51 UTC, ibramgusti commented on src/view/CSArticle/CSArticle.tsx
> +                setContentArticle(resp.data.data.attributes.content.split('\n').filter((item: string) => item.length));
oh iya itu buat state markdownya, yang di CSArticle lupa blm saya pakein ReactMarkdown

2022-03-01 10:54 UTC, rennols commented on src/component/CSDocsContent.tsx
> +                            const childs = React.Children.toArray(children)
https://reactjs.org/docs/react-api.html#reactchildrentoarray
> Useful if you want to manipulate collections of children in your render methods, especially if you want to reorder or slice this.props.children before passing it down

di code kamu kan ngga ngapa ngapain, jadi ngga perlu call toArray harusnya

2022-03-01 11:13 UTC, ibramgusti commented on src/component/CSDocsContent.tsx
> +                            const childs = React.Children.toArray(children)
iya pak kemarin baca itu, nangkepnya saya dia itu nge flattin array kali aja ada yg nested atau semacamnya.. sebenernya ngga terlalu paham sih, jadi ini make toString aja ya pak?

2022-03-01 11:19 UTC, rennols commented on src/component/CSDocsContent.tsx
> +                            const childs = React.Children.toArray(children)
kok toString, lihat snippet di awal, langsung aja kayak gitu harusnya bisa

2022-03-02 03:39 UTC, rennols commented on src/component/CSDocsContent.tsx
> +        table_content: string
Samain aja sama yang laen, tableContent

2022-03-02 03:40 UTC, rennols commented on src/component/CSDocsContent.tsx
> +    const generateSlug = (strVars: React.ReactNode & React.ReactNode[]) => {
Bukan str dong kalo typenya ReactNode

2022-03-02 03:41 UTC, rennols commented on src/component/CSDocsContent.tsx
> +                        a({ children, href }) {
Ini masih bukan key value, bukannya kemaren sepakat buat key value

2022-03-02 03:42 UTC, rennols commented on src/component/CSDocsContent.tsx
> +                    h4: ({ children }) => {
Kalo ngeganti sesuatu itu jangan cuma sebagian, disini key value tapi yang lain belum

2022-03-02 03:44 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +                    {/* Loop to render doc list */}
Kalo function namenya udah diganti, comment ini ya dihapus dong

2022-03-02 03:54 UTC, rennols commented on src/view/CSDocsPage/CSDocsPage.tsx
> +                    {/* Loop to render doc list */}
hapus commentnya

2022-03-02 05:34 UTC, rennols requested changes

2022-03-02 05:34 UTC, rennols commented on src/component/CSDocsContent.tsx
> +    if (strError !== '') return (
itu bisa langsung check string
sama syntaxnya if nya pake bracket aja biar jelas, kalo kayak gitu bacanya susah
```js
if (strError) {
  return ()
}

return()
```

2022-03-02 05:38 UTC, ibramgusti commented on src/component/CSDocsContent.tsx
> +    if (strError !== '') return (
berarti strError ini defaultnya undefined aja gitu pak @rennols ?

2022-03-02 07:31 UTC, rennols approved these changes

2022-03-02 07:31 UTC, merged