Create Home page
codescapes-io/codescapes-io.github.io pull request #4
Opened 2022-01-20 10:28 UTC by ibramgusti

#1 
i have an issue

response dari strapi aricles http://api.codescapes.io/api/articles berupa object yang didalamnya ada array content dan object meta.

```js
state = {
        contents: [],
        error: null,
    }

componentDidMount = async () => {
        try {
            const response = await axios.get('http://api.codescapes.io/api/articles');
            this.setState({ contents: response.data.data });
        } catch (error) {
            console.log(error);
        }
    }
```
harusnya ketika manggil content[0].attributes.title bisa render title dari strapi tapi di programnya attributes ngga kebaca, kalau dilihat dari error msg nya state.content type nya never[]
agak stuck disini sih pak

2022-01-20 10:28 UTC, ibramgusti commented
untuk penamaan file dan variable mungkin masih banyak yg salah, setelah ini saya benahi

2022-01-20 11:11 UTC, rennols commented
ya itu masalah typingnya, mesti bikin interface

satu hal, semua pake function component aja, itu class component tolong diganti

2022-01-21 07:31 UTC, ibramgusti commented
untuk styling dipisah ya pak? lalu make scss?

2022-01-21 07:47 UTC, rennols requested changes

2022-01-21 07:47 UTC, rennols commented on src/view/CSHomePage.tsx
> +                        <img key={el.id} src={`http://api.codescapes.io${el.attributes.url}`} alt="" />
use .env to store server base url

2022-01-21 09:24 UTC, rennols commented
> untuk styling dipisah ya pak? lalu make scss?

kalo pagenya banyak mending dipisah, css gapapa

2022-01-21 09:48 UTC, ibramgusti commented on src/view/CSHomePage.tsx
> +                        <img key={el.id} src={`http://api.codescapes.io${el.attributes.url}`} alt="" />
make dotenv ya pak?

2022-01-21 12:39 UTC, rennols commented on src/view/CSHomePage.tsx
> +                        <img key={el.id} src={`http://api.codescapes.io${el.attributes.url}`} alt="" />
ngga perlu, react udah bisa baca .env
bikin .env trus isinya
SERVER_URL=http://api.codescapes.io

trus di axios tinggal process.env.SERVER_URL kalo gasalah

2022-01-24 02:10 UTC, rennols requested changes

2022-01-24 02:10 UTC, rennols commented on src/view/CSHomePage.tsx
> +            const response = await axios.get(process.env.REACT_APP_HOMEPAGE_API ? process.env.REACT_APP_HOMEPAGE_API : '');
ngga semuanya juga masuk ke .env, base urlnya aja
http://api.codescapes.io

sama file .env di push ya
kayaknya kena gitignore

2022-01-24 02:22 UTC, rennols approved these changes

2022-01-24 02:22 UTC, merged