update favico and title, also update img to use env base_url
codescapes-io/codescapes-io.github.io pull request #8
Opened 2022-01-26 03:37 UTC by ibramgusti

untuk issu create blog page, masih progress di strapi
#7 #6

2022-01-26 04:06 UTC, rennols requested changes

2022-01-26 04:06 UTC, rennols commented on src/view/CSBlogPage.tsx
> +    );
bukannya ini harusnya udah fetch dari api?

2022-01-26 04:06 UTC, rennols commented on src/component/CSCardArtilePopular.tsx
> +};
ini juga harusnya fetch dari api

2022-01-26 04:06 UTC, rennols commented on src/component/CSCardArtilePopular.tsx
> +const CSCardArtilePopular = () => {
fix typo

2022-01-26 04:06 UTC, rennols commented on src/component/CSCardArticle.tsx
> +        <div className='container-article-ads'>
ini juga fetch dari api

2022-01-26 04:06 UTC, rennols commented on public/index.html
> +  <div id="root"></div>
fix indentationnya

2022-01-26 04:06 UTC, rennols commented on src/assets/style/CSBlogPage.css
> +    background-image: url('/public/image/BlogHeroImg.png');
img harusnya fetch dari api
bikin aja single types buat Blog
trus juga dia carousel ya, ada navnya dibawah
![image](https://user-images.githubusercontent.com/10262370/151102279-50f64ecf-6873-4167-9170-edbeb69c603e.png)

2022-01-26 04:07 UTC, ibramgusti commented on src/view/CSBlogPage.tsx
> +    );
iyaa pak, masih progress

2022-01-27 06:19 UTC, ibramgusti commented
sementara sudah make strapi dan carouselnya uda jalan, kalau reviewnya benar mau saya coba tambahin transition dikit

2022-01-27 06:20 UTC, ibramgusti commented
oh iya sama untuk relation ke user gimana ya pak manggilnya, saya coba https://api.codescapes.io/api/articles?populate=categories,users ngga keluar usernya, mungkin saya manggilnya salah

2022-01-27 06:32 UTC, rennols requested changes

2022-01-27 06:32 UTC, rennols commented on public/index.html
>    <meta name="description" content="Web site created using create-react-app" />
hmmm, yang berubah malah indentation comment, bukan html element

2022-01-27 06:32 UTC, rennols commented on src/assets/style/CSBlogPage.css
> +    /* background-image: url('/public/image/BlogHeroImg.png'); */
no unused comment

2022-01-27 06:32 UTC, rennols commented on src/assets/style/CSBlogPage.css
> +    /* background-image: url('/public/image/BlogHeroImg.png'); */
no unused comment

2022-01-27 06:32 UTC, rennols commented on src/component/CSCardArticle.tsx
> +                /> */}
no unused comment

2022-01-27 06:32 UTC, rennols commented on src/view/CSBlogPage.tsx
> +            setPopularArticle(articles.sort((a, b) => {
sortnya dari server aja
[Strapi sort & pagination](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/sort-pagination.html#sort-using-2-fields)

2022-01-27 06:32 UTC, rennols commented on src/view/CSBlogPage.tsx
> +                    /> */}
no unused comment

2022-01-27 06:32 UTC, rennols commented on src/view/CSBlogPage.tsx
> +                }
ini tujuannya apa? knp kok kalo index > 2 return null?

2022-01-27 06:39 UTC, ibramgusti commented on src/view/CSBlogPage.tsx
> +                }
articles kan panjangnya 4 (total seluruh article) saya batis untuk nampilin 3 article, nnti dibawah bakal ada button see more

2022-01-27 06:40 UTC, ibramgusti commented on src/view/CSBlogPage.tsx
> +                    /> */}
oh iya ini niatnya biar ngga looping component hero slider, propsnya manggil lewat index, tapi kalo aku coba make index selalu erro 'attributes untracked' atau semacamnya intinya attributes ngga kebaca

2022-01-27 06:41 UTC, ibramgusti commented on src/view/CSBlogPage.tsx
> +                    /> */}
baiknya loop aja atau make index pak, pastinya mungkin make index tp error gitu pak

2022-01-27 06:45 UTC, ibramgusti commented on public/index.html
>    <meta name="description" content="Web site created using create-react-app" />
head sama body sdh saya tab 1x pak? commentnya kelebihan tab pak?

2022-01-27 06:52 UTC, rennols commented
> oh iya sama untuk relation ke user gimana ya pak manggilnya, saya coba https://api.codescapes.io/api/articles?populate=categories,users ngga keluar usernya, mungkin saya manggilnya salah

nama fieldnya users_permissions_user, harusnya ya https://api.codescapes.io/api/articles?populate=categories,users_permissions_user

2022-01-27 07:00 UTC, ibramgusti commented
> > oh iya sama untuk relation ke user gimana ya pak manggilnya, saya coba https://api.codescapes.io/api/articles?populate=categories,users ngga keluar usernya, mungkin saya manggilnya salah
> 
> nama fieldnya users_permissions_user, harusnya ya https://api.codescapes.io/api/articles?populate=categories,users_permissions_user

oh iya" pak, bisa

2022-01-27 09:34 UTC, rennols commented on src/view/CSBlogPage.tsx
> +                }
ini pake limit aja

2022-01-27 10:05 UTC, ibramgusti commented on src/view/CSBlogPage.tsx
> +                }
oh iya pak paham", sebelumnya uda aku limit lewat pagination cuman karena gatau flownya jadi aku balikin lagi kaya gitu, noted pak

2022-01-31 02:44 UTC, rennols approved these changes

2022-01-31 02:46 UTC, merged